React/ React Native udemy course
dwang134/monster-rolodex-ts pull request #1
Opened 2022-11-05 02:30 UTC by dwang134

# Title: React/ React Native ZTM Section 03 (October 31st → November 5th)
## _Summary: Covers course material from section 3 chapters 27-68_

### Chapter 27: Class Components (changed to React Hooks with Typescript)
- changed react default function component syntax to class syntax
- import {Component} from 'react'
- class App extends Component{}
- render(){} with return ()

### Chapter 28: Component state (changed to useState hook)
- implemented constructor () method and called super() which calls the constructor the class extends from: Component
- instantiated class state with this.state {} object and created name property
- used { } braces to access value of this.state.name

### Chapter 29: onClick state hook
- added onClick property onto button and called setName function to update the name state
- React will only perform a repaint when a state is a different object in memory

### Chapter 30: states and shallow merge (Switched to React Hooks)
- shallow merge: look for the key in the current state obj and update them with the current one but will replace anything deeper than the first level
- to prevent shallow merge, when changing states you must ensure you change the object properties accordingly

2022-11-08 21:59 UTC, hsiangchiyang requested changes

2022-11-08 21:59 UTC, hsiangchiyang commented on src/App.tsx
> +  //useState hooks
Remove these lines. They are not needed.

2022-11-08 21:59 UTC, hsiangchiyang commented on src/App.tsx
> +    // componentDidMount(
Remove these lines.

2022-11-08 21:59 UTC, hsiangchiyang commented on types/Monster.ts
> +//prototyping for Monster object
Remove the unused model.

2022-11-14 23:18 UTC, dwang134 reviewed
removing commented code resolved.

2022-11-14 23:40 UTC, hsiangchiyang commented
Please merge this to main branch and start a new PR for the next topic.

2022-11-15 23:24 UTC, merged